Revert "[PerformanceInspector] Register extension"
error: fatal: submit not permitted

fatal: one or more reviews failed; review output above

This reverts commit 82e807a131969140605ac43ea2ab277a1fca4a22.

Change-Id: I586577839fe8876f2adcd43ee7f0539bd4fe4c8c