Disabled for the moment due to misconfiguration in Git
Checking AdManager
Initialized empty Git repository in /resources/projects/mediawiki-extensions/extensions/AdManager/.git/
error: The requested URL returned error: 401 while accessing https://gerrit.wikimedia.org/r/p/mediawiki/extensions/AdManager.git/info/refs
fatal: HTTP request failed
Clone of 'https://gerrit.wikimedia.org/r/p/mediawiki/extensions/AdManager.git' into submodule path 'extensions/AdManager' failed