Revert "Update Maps to 7.20.1"
This reverts commit badde1233291aa7d5f89342d622fb84787f0b05c.

Reason for revert: Causes exceptions on all pages -
Error: invalid magic word: 'coordinates'

Change-Id: Iee420ec9b3810348db01a02cf2312e133bfeb5b9